name: Flask CI/CD

on:
  push:
    branches:
      - master  # This runs the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use Python 3.x (e.g., 3.8)

    - name: Install dependencies
      run: |
        python3 -m venv env_project
        source env_project/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source env_project/bin/activate
        pip list
        flask run
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'

  #   - name: Install dependencies
  #     run: |
  #       python -m venv venv
  #       source venv/bin/activate
  #       pip install -r requirements.txt

  #   - name: Deploy to Heroku
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: |
  #       curl https://cli-assets.heroku.com/install.sh | sh
  #       heroku login -i
  #       git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<your-app-name>.git main
