name: Flask CI/CD

on:
  push:
    branches:
      - master  # This runs the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8

      - name: Install dependencies
        run: |
          python3 -m venv env_project
          source env_project/bin/activate
          pip install -r requirements.txt

      # Remove the Run tests step
      # - name: Run tests
      #   run: |
      #     source env_project/bin/activate
      #     pip list
      #     pytest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}          # e.g., 192.168.0.111
          username: ${{ secrets.SERVER_USER }}    # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # SSH private key
          port: 22                                # SSH port, default is 22
          script: |
            # Navigate to your project directory
            cd /path/to/your/project

            # Pull the latest changes
            git pull origin master

            # Activate the virtual environment
            source env_project/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart the Flask application
            # This depends on how you manage your Flask app. For example, if using systemd:
            sudo systemctl restart your-flask-app.service
